<a href="https://colab.research.google.com/github/111Vidya/Core-Python-IDLE-Shell/blob/main/Jul_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#What is Nympy?
# Numpy is a powerful numerical computing library in python and work with arrays
import numpy as np

In [ ]:
#Creating Array- ordered data type, homogeneous data type
ar1=np.array([1,2,3,4,5]) #1D array
ar2=np.array([[1,2,3],[4,5,6]]) #2D array

In [ ]:
#Array attributes
ar1.shape

(5,)

In [ ]:
ar2.shape # 2 rows 3 cols

(2, 3)

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
type(ar1)

numpy.ndarray

In [ ]:
#Array indexing and slicing
ar1[0]

1

In [ ]:
#row 1 index 2
ar2[1,2]

6

In [ ]:
ar2[0,2]

3

In [ ]:
ar1[1:4]

array([2, 3, 4])

In [ ]:
#update array value for index 0
ar1[0]=10
ar1

array([10,  2,  3,  4,  5])

In [ ]:
ar3=np.array([1,2,3])
ar4=np.array([4,5,6])

In [ ]:
ar3+ar4 # addition of arrays dont result in concatanation

array([5, 7, 9])

In [ ]:
ar3*ar4 # multilication no concat like list

array([ 4, 10, 18])

In [ ]:
print(np.sqrt(ar3))
print(np.mean(ar3))

[1.         1.41421356 1.73205081]
2.0


In [ ]:
#Broadcasting -1D array is repeated for the next row in 2D
ar5=np.array([[1,2,3],[4,5,6]])
ar6=np.array([1,0,1])
ar5+ar6

array([[2, 2, 4],
       [5, 5, 7]])

In [ ]:
#Reshaping arrays- arange=array range
a=np.arange(12)
a.shape

(12,)

In [ ]:
#reshape to 3 rows and 4 cols
ar7=np.arange(12).reshape(3,4)
ar7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#reshape in to 2 arrays of 2rows and 3cols
arr7=np.arange(12).reshape(2,2,3)
arr7

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# -1 to flatten the array to 1D
new_arr=arr.reshape(-1)
new_arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
#stacking and splitting arrays
arr8=np.array([[1,2],[3,4]])
arr9=np.array([[5,6],[7,8]])

In [ ]:
#Vertical stacking
np.vstack((arr8,arr9))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#Horizontal stacking
h_arr=np.hstack((arr8,arr9))
np.hstack((arr8,arr9))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Split data-along axis=0 along rows
new_array=np.split(h_arr,2)
new_array

[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]

In [ ]:
# Split data-along axis=1 along cols
col_split=np.split(h_arr,2,axis=1)
col_split

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [ ]:
#Linear algebra operations. DOT Prod or matrix multiplcation
#no of cols in 1st matrix shud be = no of rows in 2nd col
arr10=np.array([[1,2],[3,4]])
arr11=np.array([[5,6],[7,8]])
np.dot(arr10,arr11)

array([[19, 22],
       [43, 50]])

In [ ]:
#no of cols in 1st matrix shud be = no of rows in 2nd col
arr10=np.array([[1,2,3],[3,4,6]]).reshape(3,2)
arr11=np.array([[5,6],[7,8]])
np.dot(arr10,arr11)

array([[19, 22],
       [36, 42],
       [62, 72]])

In [ ]:
arr10=np.array([[1,2,3],[3,4,6]]).reshape(3,2)
arr10

array([[1, 2],
       [3, 3],
       [4, 6]])

In [ ]:
#Solving Linear Equations
# 2x + 3y = 8
# 3x + 4y = 11
a=np.array([[2,3],[3,4]])
b=np.array([8,11])
np.linalg.solve(a,b) # x=1,y=2

array([1., 2.])